swagger: '2.0'
info:
  description: Project RED ADM Core API
  version: 1.0.0
  title: ADM Core API
  # put the contact info for your development or API team
  contact:
    email: david.hollema@edf-re.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

definitions:
  Point:
    type: object
    required: 
    - type
    - coordinates 
    properties:
      type:
        type: string
        #example: Point
      coordinates:
        type: array
        minItems: 2
        maxItems: 2
        #example: [126.10, 53.47]
        items:
          type: number
  Project:
    type: object
    required:
    - id
    - name
    - type
    - status
    - geometry
    properties:
      id:
        type: string
        format: uuid
        #example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        #example: Milo
      type:
        type: string
        enum:
          - Wind - Onshore
          - Wind - Offshore
          - Solar
          - Storage
          - Bioenergy - Biogas
          - Bioenergy - Biomass
          - Hybrid
      status:
        type: string
        enum:
          - Development - Feasibility
          - Development - Mid Stage
          - Development - Advanced Stage
          - Implementation
          - Operational - Generation
          - Operational - 3rd Party O&M
          - Decommissioned
          - Inactive
      geometry:
        $ref: '#/definitions/Point'
# basePath: /adm-core-api/1.0.0
schemes:
 - https
paths:
  /projects:
    get:
      summary: Gets all projects.
      operationId: getProjects
      tags:
      - Projects
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
        400:
          description: Not Found
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#      x-amazon-apigateway-integration:
#        httpMethod: post
#        type: aws_proxy
#        uri: 
#        responses: {}
#    post:
#      summary: Adds a new project.
#      operationId: addProject
#      tags:
#      - Projects
#      produces:
#      - application/json
#      parameters:
#        - in: body
#          name: project
#          description: The project to create.
#          schema:
#            $ref: '#/definitions/Project'
#          
#      responses:
#        201:
#          description: Created
#          schema:
#            $ref: '#/definitions/Project'
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#        400:
#          description: Bad Request Body
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#    options:
#      summary: CORS support
#      description: |
#        Enable CORS by returning correct headers
#      consumes:
#        - application/json
#      produces:
#        - application/json
#      tags:
#        - CORS
#      x-amazon-apigateway-integration:
#        type: mock
#        requestTemplates:
#          application/json: |
#            {
#              "statusCode" : 200
#            }
#        responses:
#          "default":
#            statusCode: "200"
#            responseParameters:
#              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
#              method.response.header.Access-Control-Allow-Methods : "'*'"
#              method.response.header.Access-Control-Allow-Origin : "'*'"
#            responseTemplates:
#              application/json: |
#                {}
#      responses:
#        200:
#          description: Default response for CORS method
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#  /projects/{projectId}:
#    parameters:
#      - in: path
#        name: projectId
#        description: ID of the project to get.
#        type: string
#        format: uuid
#        required: true
#    get:
#      summary: Gets a project.
#      operationId: getProject
#      tags:
#      - Projects
#      produces:
#      - application/json
#      responses:
#        200:
#          description: OK
#          schema:
#            $ref: '#/definitions/Project'
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#        400:
#          description: Not Found
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#    put:
#      summary: Updates a project.
#      operationId: updateProject
#      tags:
#      - Projects
#      produces:
#      - application/json
#      parameters:
#      - in: body
#        name: project
#        description: The project to update.
#        schema:
#          $ref: '#/definitions/Project'
#      responses:
#        200:
#          description: OK
#          schema:
#            $ref: '#/definitions/Project'
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#        400:
#          description: Not Found
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#    delete:
#      summary: Deletes a project.
#      operationId: deleteProject
#      tags:
#      - Projects
#      produces:
#      - application/json
#      responses:
#        200:
#          description: OK
#          schema:
#            $ref: '#/definitions/Project'
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#        400:
#          description: Not Found
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
#    options:
#      summary: CORS support
#      description: |
#        Enable CORS by returning correct headers
#      consumes:
#        - application/json
#      produces:
#        - application/json
#      tags:
#        - CORS
#      x-amazon-apigateway-integration:
#        type: mock
#        requestTemplates:
#          application/json: |
#            {
#              "statusCode" : 200
#            }
#        responses:
#          "default":
#            statusCode: "200"
#            responseParameters:
#              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
#              method.response.header.Access-Control-Allow-Methods : "'*'"
#              method.response.header.Access-Control-Allow-Origin : "'*'"
#            responseTemplates:
#              application/json: |
#                {}
#      responses:
#        200:
#          description: Default response for CORS method
#          headers:
#            Access-Control-Allow-Headers:
#              type: "string"
#            Access-Control-Allow-Methods:
#              type: "string"
#            Access-Control-Allow-Origin:
#              type: "string"
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /dhollema/adm-core-api/1.0.0
x-aws-api-id: 'yccx5qmo01'
